
# Site settings
title: "Spring 2016"
email: "mister.argote 小老鼠 gmail 點 com"
baseurl: "/spring16"
url: "http://s16.argote.org"
description: "Students of Mr. Argote's classes at Tzu-Ming H.S., 慈明 in the spring semester of 2016."

permalink: pretty

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
twitter_username: "mrargote"
github_repo: "MrArgote/spring16"
LINE_ID: "antonioargote"
