
# Site settings
title: "Spring 2016"
email: "mister.argote 小老鼠 gmail 點 com"
baseurl: ""
url: "http://s16.argote.org"
description: "Students of Mr. Argote's classes at Tzu-Ming H.S., 慈明 in the spring semester of 2016."

permalink: pretty

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/one"
      type: "posts"
    values:
      class: "英一"
  -
    scope:
      path: "_posts/two"
      type: "posts"
    values:
      class: "英二"
  -
    scope:
      path: "_posts/pu"
      type: "posts"
    values:
      class: "普二"
  -
    scope:
      path: "_posts/three"
      type: "posts"
    values:
      class: "英三"

# Build settings
markdown: kramdown
twitter_username: "mrargote"
github_repo: "MrArgote/spring16"
LINE_ID: "antonioargote"
